name: Build index

on:
    workflow_dispatch:
    push:
      branches:
        - master
      paths:
        - 'extensions/**.json'
        - 'tags.json'
        - 'index.json'

permissions:
    contents: write

jobs:
    build-extension-index-jobs:
        runs-on: ubuntu-latest

        steps:
        - name: Check if base repository
          run: |
            if [ "${{ github.repository }}" != "AUTOMATIC1111/stable-diffusion-webui-extensions" ]; then
              echo "This is a forked repository. Exiting..."
              exit 0
            fi

        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 2

        - name: Setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        - name: Build extension index
          run: python ./build_index.py

        - name: Get last commit message
          id: last-commit-message
          run: |
            echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

        - name: Commit
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: ${{ steps.last-commit-message.outputs.msg }}
            commit_options: '--amend --no-edit'
            file_pattern: '*.json'
            push_options: '--force'
            skip_fetch: true
